# coding: utf-8

"""
    CyberProof Platform Backend API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AdaptiveCardTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'entity': 'str',
        'name': 'str',
        'source': 'str',
        'type': 'str',
        'template': 'str'
    }

    attribute_map = {
        'id': '_id',
        'entity': 'entity',
        'name': 'name',
        'source': 'source',
        'type': 'type',
        'template': 'template'
    }

    def __init__(self, id=None, entity=None, name=None, source=None, type=None, template=None):  # noqa: E501
        """AdaptiveCardTemplate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._entity = None
        self._name = None
        self._source = None
        self._type = None
        self._template = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.entity = entity
        if name is not None:
            self.name = name
        if source is not None:
            self.source = source
        if type is not None:
            self.type = type
        self.template = template

    @property
    def id(self):
        """Gets the id of this AdaptiveCardTemplate.  # noqa: E501


        :return: The id of this AdaptiveCardTemplate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AdaptiveCardTemplate.


        :param id: The id of this AdaptiveCardTemplate.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def entity(self):
        """Gets the entity of this AdaptiveCardTemplate.  # noqa: E501


        :return: The entity of this AdaptiveCardTemplate.  # noqa: E501
        :rtype: str
        """
        return self._entity

    @entity.setter
    def entity(self, entity):
        """Sets the entity of this AdaptiveCardTemplate.


        :param entity: The entity of this AdaptiveCardTemplate.  # noqa: E501
        :type: str
        """
        if entity is None:
            raise ValueError("Invalid value for `entity`, must not be `None`")  # noqa: E501
        allowed_values = ["alert", "observable", "enrichment"]  # noqa: E501
        if entity not in allowed_values:
            raise ValueError(
                "Invalid value for `entity` ({0}), must be one of {1}"  # noqa: E501
                .format(entity, allowed_values)
            )

        self._entity = entity

    @property
    def name(self):
        """Gets the name of this AdaptiveCardTemplate.  # noqa: E501


        :return: The name of this AdaptiveCardTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AdaptiveCardTemplate.


        :param name: The name of this AdaptiveCardTemplate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def source(self):
        """Gets the source of this AdaptiveCardTemplate.  # noqa: E501


        :return: The source of this AdaptiveCardTemplate.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this AdaptiveCardTemplate.


        :param source: The source of this AdaptiveCardTemplate.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def type(self):
        """Gets the type of this AdaptiveCardTemplate.  # noqa: E501


        :return: The type of this AdaptiveCardTemplate.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AdaptiveCardTemplate.


        :param type: The type of this AdaptiveCardTemplate.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def template(self):
        """Gets the template of this AdaptiveCardTemplate.  # noqa: E501


        :return: The template of this AdaptiveCardTemplate.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this AdaptiveCardTemplate.


        :param template: The template of this AdaptiveCardTemplate.  # noqa: E501
        :type: str
        """
        if template is None:
            raise ValueError("Invalid value for `template`, must not be `None`")  # noqa: E501

        self._template = template

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdaptiveCardTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
