# coding: utf-8

"""
    CyberProof Platform Backend API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.embed_playbook_step import EmbedPlaybookStep  # noqa: F401,E501


class EmbedPlaybook(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'nodes': 'list[EmbedPlaybookStep]'
    }

    attribute_map = {
        'id': '_id',
        'name': 'name',
        'nodes': 'nodes'
    }

    def __init__(self, id=None, name=None, nodes=None):  # noqa: E501
        """EmbedPlaybook - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._nodes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.nodes = nodes

    @property
    def id(self):
        """Gets the id of this EmbedPlaybook.  # noqa: E501


        :return: The id of this EmbedPlaybook.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EmbedPlaybook.


        :param id: The id of this EmbedPlaybook.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this EmbedPlaybook.  # noqa: E501


        :return: The name of this EmbedPlaybook.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EmbedPlaybook.


        :param name: The name of this EmbedPlaybook.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def nodes(self):
        """Gets the nodes of this EmbedPlaybook.  # noqa: E501


        :return: The nodes of this EmbedPlaybook.  # noqa: E501
        :rtype: list[EmbedPlaybookStep]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this EmbedPlaybook.


        :param nodes: The nodes of this EmbedPlaybook.  # noqa: E501
        :type: list[EmbedPlaybookStep]
        """
        if nodes is None:
            raise ValueError("Invalid value for `nodes`, must not be `None`")  # noqa: E501

        self._nodes = nodes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmbedPlaybook):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
