# coding: utf-8

"""
    CyberProof Platform Backend API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MetamodelAvailableValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value': 'str',
        'color': 'str',
        'read_only': 'bool'
    }

    attribute_map = {
        'value': 'value',
        'color': 'color',
        'read_only': 'readOnly'
    }

    def __init__(self, value=None, color=None, read_only=None):  # noqa: E501
        """MetamodelAvailableValues - a model defined in Swagger"""  # noqa: E501

        self._value = None
        self._color = None
        self._read_only = None
        self.discriminator = None

        self.value = value
        if color is not None:
            self.color = color
        if read_only is not None:
            self.read_only = read_only

    @property
    def value(self):
        """Gets the value of this MetamodelAvailableValues.  # noqa: E501


        :return: The value of this MetamodelAvailableValues.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this MetamodelAvailableValues.


        :param value: The value of this MetamodelAvailableValues.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def color(self):
        """Gets the color of this MetamodelAvailableValues.  # noqa: E501


        :return: The color of this MetamodelAvailableValues.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this MetamodelAvailableValues.


        :param color: The color of this MetamodelAvailableValues.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def read_only(self):
        """Gets the read_only of this MetamodelAvailableValues.  # noqa: E501


        :return: The read_only of this MetamodelAvailableValues.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this MetamodelAvailableValues.


        :param read_only: The read_only of this MetamodelAvailableValues.  # noqa: E501
        :type: bool
        """

        self._read_only = read_only

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetamodelAvailableValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
