# coding: utf-8

"""
    CyberProof Platform Backend API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.webhook_authentication import WebhookAuthentication  # noqa: F401,E501


class Webhook(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'trigger': 'str',
        'url': 'str',
        'authentication': 'WebhookAuthentication',
        'organization': 'str',
        'created': 'date',
        'modified': 'date'
    }

    attribute_map = {
        'id': '_id',
        'name': 'name',
        'trigger': 'trigger',
        'url': 'url',
        'authentication': 'authentication',
        'organization': 'organization',
        'created': 'created',
        'modified': 'modified'
    }

    def __init__(self, id=None, name=None, trigger=None, url=None, authentication=None, organization=None, created=None, modified=None):  # noqa: E501
        """Webhook - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._trigger = None
        self._url = None
        self._authentication = None
        self._organization = None
        self._created = None
        self._modified = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.trigger = trigger
        self.url = url
        if authentication is not None:
            self.authentication = authentication
        if organization is not None:
            self.organization = organization
        if created is not None:
            self.created = created
        if modified is not None:
            self.modified = modified

    @property
    def id(self):
        """Gets the id of this Webhook.  # noqa: E501


        :return: The id of this Webhook.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Webhook.


        :param id: The id of this Webhook.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Webhook.  # noqa: E501


        :return: The name of this Webhook.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Webhook.


        :param name: The name of this Webhook.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def trigger(self):
        """Gets the trigger of this Webhook.  # noqa: E501


        :return: The trigger of this Webhook.  # noqa: E501
        :rtype: str
        """
        return self._trigger

    @trigger.setter
    def trigger(self, trigger):
        """Sets the trigger of this Webhook.


        :param trigger: The trigger of this Webhook.  # noqa: E501
        :type: str
        """
        if trigger is None:
            raise ValueError("Invalid value for `trigger`, must not be `None`")  # noqa: E501

        self._trigger = trigger

    @property
    def url(self):
        """Gets the url of this Webhook.  # noqa: E501


        :return: The url of this Webhook.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Webhook.


        :param url: The url of this Webhook.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def authentication(self):
        """Gets the authentication of this Webhook.  # noqa: E501


        :return: The authentication of this Webhook.  # noqa: E501
        :rtype: WebhookAuthentication
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication):
        """Sets the authentication of this Webhook.


        :param authentication: The authentication of this Webhook.  # noqa: E501
        :type: WebhookAuthentication
        """

        self._authentication = authentication

    @property
    def organization(self):
        """Gets the organization of this Webhook.  # noqa: E501


        :return: The organization of this Webhook.  # noqa: E501
        :rtype: str
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Webhook.


        :param organization: The organization of this Webhook.  # noqa: E501
        :type: str
        """

        self._organization = organization

    @property
    def created(self):
        """Gets the created of this Webhook.  # noqa: E501


        :return: The created of this Webhook.  # noqa: E501
        :rtype: date
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Webhook.


        :param created: The created of this Webhook.  # noqa: E501
        :type: date
        """

        self._created = created

    @property
    def modified(self):
        """Gets the modified of this Webhook.  # noqa: E501


        :return: The modified of this Webhook.  # noqa: E501
        :rtype: date
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Webhook.


        :param modified: The modified of this Webhook.  # noqa: E501
        :type: date
        """

        self._modified = modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Webhook):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
